-- UPDATES TO THE DATABASE FOR FINAL_RELEASE AFTER THE MVP_RELEASE
DROP TABLE IF EXISTS reach_out.SYSTEM_PROPERTIES;

CREATE TABLE reach_out.SYSTEM_PROPERTIES(
SP_ID int(11) NOT NULL AUTO_INCREMENT,
SP_NAME varchar(200) UNIQUE NOT NULL,
SP_VALUE varchar(200) NOT NULL,
PRIMARY KEY(SP_ID)
);

INSERT INTO reach_out.SYSTEM_PROPERTIES (SP_NAME, SP_VALUE) VALUES ("IMAGE_DIR", "C:\xampp\images");
INSERT INTO reach_out.SYSTEM_PROPERTIES (SP_NAME, SP_VALUE) VALUES ("ROOT_DIR", "C:\xampp");
INSERT INTO reach_out.SYSTEM_PROPERTIES (SP_NAME, SP_VALUE) VALUES ("API_KEY", "changeme");

DROP TABLE IF EXISTS reach_out.PASSWORD_RESET;

CREATE TABLE reach_out.PASSWORD_RESET(
PR_ID int(11) NOT NULL,
USERS_ID int(65) NOT NULL,
PR_CODE VARCHAR(100) NOT NULL,
PR_CREATE_DATE BigInt(35) NOT NULL,
PRIMARY KEY(PR_ID)
);


ALTER TABLE reach_out.listings 
ADD COLUMN LST_LOC_ID INT(11) NOT NULL AFTER LST_PRIORITY;


CREATE TABLE locations (
  LOC_ID int(11) NOT NULL AUTO_INCREMENT,
  LOC_LAT decimal(10,7) DEFAULT NULL,
  LOC_LONG decimal(10,7) DEFAULT NULL,
  PRIMARY KEY (LOC_ID)