-- UPDATES TO THE DATABASE FOR FINAL_RELEASE AFTER THE MVP_RELEASE

DROP TABLE IF EXISTS reach_out.SYSTEM_PROPERTIES;
CREATE TABLE reach_out.SYSTEM_PROPERTIES(
SP_ID int(11) NOT NULL AUTO_INCREMENT,
SP_NAME varchar(200) UNIQUE NOT NULL,
SP_VALUE varchar(200) NOT NULL,
PRIMARY KEY(SP_ID)
);

INSERT INTO reach_out.SYSTEM_PROPERTIES (SP_NAME, SP_VALUE) VALUES ("IMAGE_DIR", "C:\xampp\images");
INSERT INTO reach_out.SYSTEM_PROPERTIES (SP_NAME, SP_VALUE) VALUES ("ROOT_DIR", "C:\xampp");
INSERT INTO reach_out.SYSTEM_PROPERTIES (SP_NAME, SP_VALUE) VALUES ("API_KEY", "changeme");

DROP TABLE IF EXISTS reach_out.GROUPS;
CREATE TABLE reach_out.GROUPS(
G_ID int(11) NOT NULL AUTO_INCREMENT,
G_NAME varchar(200) UNIQUE NOT NULL,
G_DESC varchar(400) NOT NULL,
G_LOC_ID int(11) NOT NULL,
PRIMARY KEY(G_ID)
);


DROP TABLE IF EXISTS reach_out.GROUP_MEMBER;
CREATE TABLE reach_out.GROUP_MEMBER(
GM_ID int(11) NOT NULL AUTO_INCREMENT,
GM_G_ID int(11) NOT NULL,
GM_G_UID int(11) NOT NULL,
GM_U_STATUS_ID int(3) NOT NULL,
PRIMARY KEY(GM_ID)
);

DROP TABLE IF EXISTS reach_out.GROUP_LISTING;
CREATE TABLE reach_out.GROUP_LISTING(
GL_ID int(11) NOT NULL AUTO_INCREMENT,
GL_GRP_ID int(11) NOT NULL,
GL_LST_ID int(11) NOT NULL,
PRIMARY KEY(GL_ID)
);

ALTER TABLE reach_out.LISTINGS
ADD LST_VISIBILITY int(3);


DROP TABLE IF EXISTS reach_out.PASSWORD_RESET;

CREATE TABLE reach_out.PASSWORD_RESET(
PR_ID int(11) NOT NULL,
USERS_ID int(65) NOT NULL,
PR_CODE VARCHAR(100) NOT NULL,
PR_CREATE_DATE BigInt(35) NOT NULL,
PRIMARY KEY(PR_ID)
);


ALTER TABLE reach_out.LISTINGS
ADD COLUMN LST_LOC_ID INT(11) NOT NULL AFTER LST_PRIORITY;


CREATE TABLE locations (
  LOC_ID int(11) NOT NULL AUTO_INCREMENT,
  LOC_LAT decimal(10,7) DEFAULT NULL,
  LOC_LONG decimal(10,7) DEFAULT NULL,
  PRIMARY KEY (LOC_ID)
